.svgrrc
app/assets/image/Close.svg
app/assets/util/layout.ts
app/components/common/text.tsx
app/screens/index.tsx
app/screens/modal/university-map-modal.tsx
app/screens/stack.tsx
app/screens/university.tsx
declaration.d.ts
ios/Podfile.lock
metro.config.js
package.json
yarn.lock

fix: rebase conflict
:sparkles: Svg icon import, university modal screen
fix: modal
feat: navigate to main

:sparkles: University Modal

---

app/components/common/layout.tsx
app/components/common/tag.tsx
app/components/main/header.tsx
app/components/main/keyword.tsx
app/screens/home.tsx
app/screens/main.tsx
app/screens/search.tsx
app/screens/stack.tsx
ios/Podfile.lock
package.json
yarn.lock

fix: rebase conflict
feat: 검색어 전달
feat:  async storage
feat: 최근 검색어

:sparkles: Search screen

---

android/app/build.gradle
android/app/google-services.json
android/build.gradle
app/screens/index.tsx
ios/Podfile
ios/Podfile.lock
ios/nThing.xcodeproj/project.pbxproj
ios/nThing.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ios/nThing/AppDelegate.mm
ios/nThing/Info.plist
package.json
yarn.lock

:sparkles: Firebase & Google Login

---

app/components/common/autocomplete.tsx
app/screens/modal/university-map-modal.tsx
app/screens/stack.tsx
app/screens/university.tsx
app/types/common.ts

:sparkles: /college api 적용하여 autocomplete

---

app/assets/image/Down.svg
app/components/common/select.tsx
app/screens/home.tsx
app/types/common.ts
ios/nThing.xcodeproj/project.pbxproj
package.json
yarn.lock

바텀시트 셀렉트박스 추가되었습니다.
@JUNSEULGI 셀렉트 박스 open 상태에 따른 아이콘 애니메이션 부분이 있는데 그 부분 때문에 홈 스크린으로 진입시 warning이 뜰건데..
해당 라이브러리에서 open 상태를 감지할 수 있는 부분이 거기 밖에 없어서 warning을 해결할 다른 방법이 없더라구요. 이거는 나중에 만나서 같이 얘기를 해보는 게 좋을 것 같습니다. warning을 무시할지, 아니면 애니메이션을 제거할지에 대해서요..!

:sparkles: bottomsheet selectbox add

---

app/components/common/item.tsx
app/screens/home.tsx

:sparkles: heart animation

---

app/components/common/date-time-picker.tsx
app/screens/trade-regist.tsx
app/types/common.ts
ios/Podfile.lock
ios/nThing.xcodeproj/project.pbxproj
package.json
yarn.lock

특이사항
- 리베이스도 문제 없이 잘 되고, 리베이스 하면서 추가된 라이브러리 설치 후에도 빌드 문제 없이 한번에 잘 됐는데
- 깔았다가 쓰지 않게 된 react native date picker를 지운다고 yarn remove 한 후 빌드하니 build failed 뜸
- 그래서 pod deintegrate 후 pod install 다시 함

✨ 거래 날짜 선택

---

app/components/common/button.tsx

:ambulance:  카테고리 버튼 누락 수정

---

app/assets/image/icon/icon.ts

:bento: S_Caution Icon add

---

App.tsx
app/api/user.ts
app/assets/util/storage.ts
app/hooks/useApiError.tsx
app/hooks/user/index.tsx
app/observers/app-state.tsx
app/screens/index.tsx
app/screens/my-page.tsx
app/state/app.ts
app/types/user.ts
package.json
yarn.lock

- 앱 상태 체크 로직 (AppState)
앱의 상태가 활성인지 비활성인지 확인하는 로직 추가
- 토큰 설정하는 방식 수정

:sparkles:  앱상태체크 로직 추가, 토큰설정방식 수정

---

app/api/purchase.ts
app/assets/util/format.ts
app/components/trade/comment.tsx
app/components/trade/comments.tsx
app/hooks/purchase/purchase-comments.ts
app/screens/trade-regist.tsx
app/screens/trade.tsx
app/types/common.ts

- 날짜 시간대 안 맞는 문제 해결 필요
- 키보드 올라올 때 해결 필요

:sparkles: Comments api 연동

---

app/api/purchase.ts
app/screens/trade.tsx

- use-like 공통으로 적용하면서 body를 담을 수 있게 개선 필요

✨ 거래글 상세 > 좋아요 POST 요청

---

app/api/map.ts
app/assets/util/constants.ts
app/hooks/map/index.tsx
app/hooks/user/index.tsx
app/screens/home.tsx

맵 메인 화면 유저정보호출, 미로그인 유저 분기(팝업으로) 작업중

:sparkles: map 유저정보호출, 미로그인 유저 분기작업중

---

App.tsx
app/api/category.ts
app/api/college.ts
app/api/purchase.ts
app/api/user.ts
app/assets/mock/pins.ts
app/components/nmap/marker.tsx
app/components/trade/comments.tsx
app/hooks/college/index.tsx
app/hooks/college/key.ts
app/hooks/map/index.tsx
app/hooks/map/key.ts
app/hooks/purchase/key.ts
app/hooks/purchase/purchase-comments.ts
app/hooks/purchase/purchase-detail.ts
app/hooks/user/index.tsx
app/hooks/user/key.ts
app/screens/home.tsx
app/screens/index.tsx
app/screens/my-page.tsx
app/screens/trade.tsx
app/screens/university.tsx
app/types/common.ts

:arrow_up: react-query v3 => v5

---

app/hooks/map/index.tsx
app/screens/home.tsx

안쓰는 변수 및 주석 삭제, 타입 에러, 코드 스타일에서 불필요한 개행 제거

:recycle: Home 화면 elsint 에러

---

app/assets/mock/messages.ts
app/components/chat/date-separator.tsx
app/components/chat/finish-bubble.tsx
app/components/chat/message-list.tsx
app/components/chat/message.tsx
app/components/common/button.tsx
app/components/common/text.tsx
app/types/common.ts

:lipstick: chat UI 추가

---

App.tsx
app/api/category.ts
app/api/index.ts
app/api/map.ts
app/components/common/button.tsx
app/hooks/map/index.tsx
app/screens/index.tsx

response.data.data 해서 쓰고 있었는데,
axios response config에서 response.data를 반환하는 것으로 바뀌어서
data를 한번 더 찍어줘야하는 상태였음

:bug: Axios response

---

app/assets/util/time.ts
app/screens/trade-regist.tsx
app/state/trade-register.ts
package.json
yarn.lock

:sparkles: TradeRegistScreen에 zustand 적용

---

app/api/purchase.ts
app/components/trade/join.tsx
app/hooks/purchase/purchase-join.ts
app/key/purchase.ts
app/screens/trade.tsx

- api 응답값 추가되면 참여한 거래인지 확인해서 참여취소, 채팅방 가기로 처리하는 것 필요
- 추후 채팅쪽 개발되면 채팅방 id 받아서 채팅방으로 이동하는 것도 필요

:sparkles: Join purchase POST

---

App.tsx
app/api/chatting.ts
app/assets/mock/messages.ts
app/assets/util/constants.ts
app/assets/util/web-socket.ts
app/components/chat/chat-item.tsx
app/components/chat/input-toolbar.tsx
app/components/chat/message-list.tsx
app/components/chat/message.tsx
app/components/chat/web-socket-connector.tsx
app/hooks/chatting/chat-rooms.tsx
app/key/chatting.ts
app/screens/chat-list/opened-trade.tsx
app/screens/chatting.tsx
app/screens/home.tsx
app/screens/index.tsx
app/screens/stack.tsx
app/state/chat.ts
app/types/chat.ts
ios/nThing.xcodeproj/project.pbxproj
package.json
yarn.lock

채팅 기능 완료는 안되었지만 코드 양이 너무 많아져서, 웹소켓 연결해서 채팅방 입장하고 메시지 주고 받는 데까지 끊고 가겠습니다!
- 채팅 관련 리팩토링
- 메시지 타입에 맞게 기존 데이터 및 컴포넌트 수정
- 웹소켓 stomp 연결 로직

✨ 채팅 웹소켓 연결

---

App.tsx
app/hooks/map/index.tsx
app/screens/home.tsx
app/screens/index.tsx
app/screens/main.tsx
app/screens/modal/university-map-modal.tsx
app/screens/stack.tsx
app/types/common.ts

fix: 로그인 안하고 나중에 하기 해서 선택된 학교 없을 때

:sparkles: 선택된 학교 위치로 지도 표시
